### ISSUE TITLE
Front page: replace Latest Awards with latest weekly leaders

### ISSUE THREAD

**Issue by stickster** [fedora-infra/tahrir#293]
Justification: Latest awards are almost always one of the very few lowest-level badges, and it's not clear that everyone who gets those has yet become "sticky" with the project.

**Comment by oddshocks** [comment]
I'd like to make a few changes to the front page columns. Idea:
- We keep the Latest Awards list, because even though it has newbie badges, it's a nice feed to have (plus it updates in real-time, with an animation)
- We remove the Newcomers list, instead having a text banner above the columns reading something like "Welcome to our newest Badger, <user> <time ago>"
- We add Weekly Leaders, as you suggested
- Probably get rid of Awesome People, as it suffers from the same problem as the leaderboard, showing always the same 10% of people, essentially, including inactive people (not sure what to replace it with yet)

**Comment by ralphbean** [comment]
Yeah, upon reading this, I'd like to keep the Latest Awards pane too.

Let's replace the newcomers list and the awesome people list with the weekly and monthly leaders.
