### ISSUE TITLE
Leaderboard page: change default lineup

### ISSUE THREAD

**Issue by stickster** [fedora-infra/tahrir#294]
It's easy for the all-time leader roster to reflect the old guard. It would be more motivational to see a monthly leaderboard, which is likely to be more dynamic in a bigger project. So replace the default leaderboard with the latest monthly list, and include a link to the all-time leaderboard for those who are interested.

**Comment by oddshocks** [comment]
+1 from me, easy fix
So you wouldn't be listed at all unless you've earned a badge that month? I wonder if anyone would be bummed to find out that even though they were actively working on earning badges during a month, they aren't listed on the leaderboard, because they didn't earn any badges. I guess it's not a big deal. We could have a message like, "You haven't earned any badges this month, but overall, you're ranked X"

**Comment by pypingou** [comment]
Missed the last sentence: ``include a link to the all-time leaderboard for those who are interested.`` ;-)

**Comment by oddshocks** [comment]
I didn't miss it, but I can see how it looks that way. :) I guess what I should have said is, "we should ensure we make it clear that the leaderboard is just for users who have earned badges that month". I'm probably being sensitive. I just don't want anyone who consistently contributes to Fedora to get the notion that they've fallen out of favour because they're on the "archive leaderboard". The message I suggested we have at the top of the page was me restating what stickster said about having a link somewhere to the all-time leaderboard. So I think we're all on the same page. :)

**Comment by oddshocks** [comment]
Oh! -- Important question: We want to show which of the below:
- A leaderboard ranked by "all time badges" for users who have earned at least one in the past week
OR
- A leaderboard ranked by "badges earned this month", with users earning 0 badges being excluded
