### ISSUE TITLE
Summer Coder badge tooltip contains an erroneous backslash

### ISSUE THREAD

**Issue by morxa** [fedora-infra/tahrir#361]
The [Summer Coder badge](https://badges.fedoraproject.org/badge/summer-coder)'s tooltip contains a backslash, it reads:

> You participated in a summer coding program (GSoC, Outreachy, internship) for Fedora\\!

I hope you don't consider this rude nitpicking... :-)

**Comment by jflory7** [comment]
Hi, so this is definitely a bug! And as the one who pushed it, I can add some extra context.

This badge was edited using the the `edit-badge` script on the badges-backend01 server. An exclamation point wasn't escaped when editing the badge, so I added `\!` so that the script would escape this in Bash. However, it seems that the tooltip interprets it literally, unlike on the badge description page. This is why badges with exclamation points initially have it display correctly, but any badge that was edited does not.
