### ISSUE TITLE
Can't change Avatar

### ISSUE THREAD

**Issue by dadreggors** [fedora-infra/tahrir#387]
I can't change my avatar. I get a 403 ("CSRF verification failed. Request aborted.") error when clicking on "Change Avatar". 

Full Error:

> Forbidden (403)
CSRF verification failed. Request aborted.

> You are seeing this message because this HTTPS site requires a 'Referer header' to be sent by your Web browser, but none was sent. This header is required for security reasons, to ensure that your browser is not being hijacked by third parties.

> If you have configured your browser to disable 'Referer' headers, please re-enable them, at least for this site, or for HTTPS connections, or for 'same-origin' requests.

> More information is available with DEBUG=True.

**Comment by justwheel** [comment]
Hi @ddreggors, thanks for filing this. This issue is probably related to #383. A similar issue was also filed [here](https://pagure.io/fedora-badges/issue/620).

I am actually not sure if this is a bug with Tahrir or an issue with Libravatar. If it is an issue with Libravatar, then we should close this as a duplicate of #383. If it is an issue with Tahrir, then we should keep it open. I'm not informed enough to know the difference, but I think Libravatar has closed down parts of their infrastructure, so I think it is an issue on their end.

@sayanchowdhury @nbebout @puiterwijk @pypingou Do you know whether this issue lies on Tahrir or with Libravatar?

**Comment by cverna** [comment]
This seems to be working as expected with the new libravatar. Closing feel free to reopen if you still have issues.
