### ISSUE TITLE
As a Contributor I want to know how to get started to create the rules.yaml so that it is easier to create new badges

### ISSUE THREAD

**Issue by cverna** [fedora-infra/tahrir#408]
TBD.

#### Acceptance Criteria

**Comment by justwheel** [comment]
I think this one is important because of how the type of badges we deploy in the last three or four years changed. Originally, there were many more automated badges being pushed, triggered by a fedmsg event. Nowadays, few new badges are added with automated rules and more manual badges are created. I think this is not a sustainable approach because every manual badge requires an individual person to "maintain" the award status of the badge. This is an often forgotten task and I think simplifying the writing of rules will help us drive more fun, interesting, and exciting badges into the application.
