### ISSUE TITLE
As an Individual Badge maintainer I would like the process to award a badge to be more scalable so that I can mass award badges.

### ISSUE THREAD

**Issue by cverna** [fedora-infra/tahrir#413]
TBD.

#### Acceptance Criteria

**Comment by justwheel** [comment]
Especially useful for Events badges, like Flock event badges. There is an existing mass-awarding functionality in the Tahrir admin portal, but it requires a CSV file and I've never tried it because I never have CSV-formatted data when I mass-award badges.

For me, when I have done mass-awarding of an event badge, I wish I could have a search box to look up a contributor's FAS username, full name, or email address and quickly award the badge. My biggest frustration today is waiting 30-45 seconds to award a single badge to a single user.
