### ISSUE TITLE
As an administrator I want the process to push new badges to production as automated as possible, so that I can save time.

### ISSUE THREAD

**Issue by cverna** [fedora-infra/tahrir#418]
TBD.

#### Acceptance Criteria

**Comment by cverna** [comment]
so I wonder how much of OpenShift we can leverage here, we could maybe look at creating an source-to-image builder image for this that would grab the source from fedbage and also the rules for pagure.io/fedora-badges.

But I guess the first step is to have fedbages run in OpenShift.

Any other ideas ?
@jwflory, @sayanchowdhury and @hroncok

**Comment by hroncok** [comment]
This was my understanding: Once there is a push to pagure.io/fedora-badges a fedora messaging consumer app just runs the update as we now do manually in batcave.

**Comment by justwheel** [comment]
The success criteria for me is when a pull request is merged, the new Badge or edited Badge will appear relatively quickly in the front-end.

There should be a way to manually force a Badge to production immediately if an immediate-update automated approach is not possible. Sometimes we've pushed Badges from a booth the hour before an event or conference because the artwork was completed just in time or the request was late.
