### ISSUE TITLE
As a designer I should not be the liaison to push the badge in production.

### ISSUE THREAD

**Issue by cverna** [fedora-infra/tahrir#422]
TBD.

#### Acceptance Criteria

**Comment by cverna** [comment]
What is the action plan for that, any ideas ?

@jwflory, @KyleRConway and @sayanchowdhury

**Comment by justwheel** [comment]
@cverna I don't have an answer. I think the best solution is a way to improve notifications from Pagure issues. I can't subscribe to Fedora Badges Pagure issues without getting email notifications for all issues. What I really want is notifications ONLY when a Badge is ready to push or needs concept review by a sysadmin. We use labels for this but perhaps there is a better way.

I prefer a "push" communication model where I am actively solicited when my attention is actually needed, instead of a "pull" communication model where I am asked to look at a ticket by another contributor when it is ready.

**Comment by sayanchowdhury** [comment]
It's better if we can work on getting this automated. A lot of badges these days are the manually awarded ones which don't need the rules files. Automating it would really streamline the process.
