### ISSUE TITLE
As a designer I would like as single page where approved artwork request is available so that it is easy for me to know which request I should work on

### ISSUE THREAD

**Issue by cverna** [fedora-infra/tahrir#423]
TBD.

#### Acceptance Criteria

**Comment by cverna** [comment]
So the idea here is to use the tags from https://pagure.io/fedora-badges/issues. What are the tags applied to an issue when it is ready to be implemented ?

From what I can see : 
- artwork needed
- ??

@jwflory, @sayanchowdhury  @tanvi1699 and @KyleRConway any ideas ?

**Comment by justwheel** [comment]
> What are the tags applied to an issue when it is ready to be implemented ?

Tags are not used. There is a custom metadata (migrated from Trac) that is rarely used in practice:

![concept_reviewed custom issue metadata in Pagure repo settings](https://user-images.githubusercontent.com/4721034/57090613-384e4c00-6cd5-11e9-9bc4-77dc4eacf567.png "concept_reviewed custom issue metadata in Pagure repo settings")

@cverna I think the tags / custom issue metadata in Fedora Badges Pagure needs a closer look. Tags and metadata are not consistently used and many of them remain because that's how Trac was set up when the project lived there. It made more sense in Trac and the migration from Trac to Pagure lost functionality that we relied on when we were there.

@riecatnor or @mashaleonova may have something to add too.

Here is a full list of all existing tags in the repo if it is useful:

![All existing tags in Fedora Badges Pagure repository](https://user-images.githubusercontent.com/4721034/57090563-194fba00-6cd5-11e9-96e0-86a6d2462919.png "All existing tags in Fedora Badges Pagure repository")

**Comment by sayanchowdhury** [comment]
We can work on the tags itself, and update the docs to reflect the issues that can be worked on.
